# Generated by Django 2.1.7 on 2019-04-30 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e-reading-api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_user', models.IntegerField(default=0, null=True)),
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_user_info',
            },
        ),
        migrations.AddField(
            model_name='vocabularyfavorite',
            name='is_hard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vocabularyfavorite',
            name='type_vocabulary',
            field=models.CharField(default='NOUN', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word',
            field=models.TextField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vocabularytype',
            name='type_vocabulary',
            field=models.CharField(db_index=True, max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='requesthistory',
            unique_together={('user_id', 'word')},
        ),
        migrations.RemoveField(
            model_name='vocabularyfavorite',
            name='difficult_level',
        ),
        migrations.AlterUniqueTogether(
            name='vocabularyfavorite',
            unique_together={('user_id', 'vocabulary_id', 'type_vocabulary')},
        ),
        migrations.AlterUniqueTogether(
            name='userextend',
            unique_together={('user_id',)},
        ),
    ]
