# Generated by Django 2.1.7 on 2019-05-06 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e-reading-api', '0002_auto_20190430_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='introduction_new_feed',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='title_new_feed',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='url_new_feed',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='url_thumbnail_new_feed',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='requesthistory',
            unique_together={('user_id', 'url_new_feed')},
        ),
    ]
