# Generated by Django 2.1.7 on 2019-05-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e-reading-api', '0003_auto_20190506_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='popularity',
            field=models.BigIntegerField(default=0),
        ),
    ]
